# Generated by Django 3.1.7 on 2021-06-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_auto_20210612_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Like',
        ),
    ]
