# Generated by Django 3.1.7 on 2021-06-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_auto_20210613_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='last_accessed',
            new_name='last_edited',
        ),
    ]
